# Inline IDS/IPS demo helper (Windows PowerShell)
#
# USAGE:
#   .\inline-demo.ps1 -Step reset                          # Clear blacklist, logs, pcaps
#   .\inline-demo.ps1 -Step start                          # Start baseline services (auto-rebuild with fixes)
#   .\inline-demo.ps1 -Step attack -Protocol modbus        # Launch single protocol attacker
#   .\inline-demo.ps1 -Step attack -Protocol all           # Launch all 4 attackers (Modbus, IEC104, DNP3, OPC-UA)
#   .\inline-demo.ps1 -Step verify                         # Check blacklist and iptables
#   .\inline-demo.ps1 -Step full -Protocol modbus          # Full demo: reset + start + attack + verify
#   .\inline-demo.ps1 -Step full -Protocol all             # Full demo with all protocols (recommended)
#   .\inline-demo.ps1 -Step full -Protocol all -WithFlood  # Full demo + QoS flood attack
#
# NOTES:
#   - Script auto-creates .env with ZEEK_INTERFACE=any for DNP3 detection
#   - Auto-rebuilds firewall-monitor and ids-monitor to apply latest fixes
#   - All 4 attackers (Modbus, IEC104, DNP3, OPC-UA) should be blacklisted
#   - Use -WithFlood to test QoS congestion handling
#
# Inline IDS/IPS & QoS "Final Boss" Demo (Windows PowerShell)
param(
    [ValidateSet("reset", "start", "attack", "verify", "full")]
    [string]$Step = "verify",

    [ValidateSet("modbus", "iec104", "dnp3", "opcua", "all")]
    [string]$Protocol = "modbus",

    [switch]$WithFlood, # <--- Bật/Tắt tấn công QoS Flood

    [int]$BaselineWaitSeconds = 30,
    [int]$BetweenAttackWaitSeconds = 35,
    [int]$FinalWaitSeconds = 45
)

$ErrorActionPreference = "Stop"
$ComposeFile = "docker-compose.inline.yaml"
$env:ZEEK_INTERFACE = "any"

# Ensure .env file exists with ZEEK_INTERFACE=any for DNP3 detection
if (-not (Test-Path .env)) {
    @"
# Environment variables for docker-compose
# ZEEK_INTERFACE=any ensures tcpdump captures all network traffic (required for DNP3)
ZEEK_INTERFACE=any

# PCAP rotation interval in seconds (default: 15)
# Lower = faster detection but more files for Zeek to process
# Higher = slower detection but less processing overhead
PCAP_ROTATION_SECONDS=15
"@ | Out-File -FilePath .env -Encoding utf8
    Write-Host "[init] Created .env with ZEEK_INTERFACE=any and PCAP_ROTATION_SECONDS=15" -ForegroundColor Gray
} elseif ((Get-Content .env -Raw) -notmatch "ZEEK_INTERFACE") {
    Add-Content -Path .env -Value "`nZEEK_INTERFACE=any"
    Write-Host "[init] Added ZEEK_INTERFACE=any to .env" -ForegroundColor Gray
}
if ((Get-Content .env -Raw) -notmatch "PCAP_ROTATION_SECONDS") {
    Add-Content -Path .env -Value "`nPCAP_ROTATION_SECONDS=15"
    Write-Host "[init] Added PCAP_ROTATION_SECONDS=15 to .env" -ForegroundColor Gray
}

$baselineServices = @(
    "influxdb", "grafana", "firewall-monitor", "zeek-ids", "ids-monitor", 
    "qos-router", "modbus-server", "modbus-client", "dnp3-server", 
    "dnp3-client", "iec104-server", "iec104-client", "opcua-server", "opcua-client"
)

$attackerServices = @("modbus-attacker", "dnp3-attacker", "iec104-attacker", "opcua-attacker")

function Stop-InlineAttackers {
    Write-Host "[reset] Stop existing attacker containers and stop flood" -ForegroundColor Yellow
    
    try { docker compose -f $ComposeFile stop @attackerServices *>$null } catch {}
    
    # Kiem tra xem container co dang chay khong thi moi bam nut tat
    $isFlooderRunning = docker ps -q -f name="inline-qos-flooder"
    if ($isFlooderRunning) {
        try { docker exec inline-qos-flooder sh -lc 'pkill -f hping3 >/dev/null 2>&1 || true' *>$null } catch {}
    }
}

function Reset-InlineArtifacts {
    Stop-InlineAttackers
    Write-Host "[reset] Clear blacklist, notice log, and rotating pcaps" -ForegroundColor Yellow
    Set-Content .\zeek_scripts\blacklist.acl "# Runtime blacklist entries generated by ids_monitor.py`n# Reset before each demo run to avoid historical noise.`n"

    if (Test-Path .\zeek_logs) {
        try { Clear-Content .\zeek_logs\notice.log -ErrorAction Stop }
        catch { docker exec zeek-ids sh -c 'truncate -s 0 /opt/zeek/logs/notice.log 2>/dev/null || true' | Out-Null }
    }

    if (Test-Path .\zeek_pcaps) {
        Remove-Item .\zeek_pcaps\*.pcap -ErrorAction SilentlyContinue
        if (Test-Path .\zeek_pcaps\processed) { Remove-Item .\zeek_pcaps\processed\* -ErrorAction SilentlyContinue }
        if (Test-Path .\zeek_pcaps\failed) { Remove-Item .\zeek_pcaps\failed\* -ErrorAction SilentlyContinue }
    }
}

function Start-InlineBaseline {
    Write-Host "[start] Start inline baseline services" -ForegroundColor Yellow
    # Build images to ensure latest code changes (entrypoint.sh fix) are applied
    docker compose -f $ComposeFile build firewall-monitor ids-monitor
    docker compose -f $ComposeFile up -d @baselineServices
    Write-Host "[start] Grafana: http://localhost:3000/d/scada-lab-main/scada-lab-overview?orgId=1&refresh=5s" -ForegroundColor Green
}

function Start-Attack {
    $protocols = @($Protocol)
    if ($Protocol -eq "all") { $protocols = @("modbus", "iec104", "dnp3", "opcua") }

    # KICH HOAT L4 FLOOD NEU CO CO -WithFlood
    if ($WithFlood) {
        Write-Host "`n[attack] KICH HOAT TAN CONG QOS FLOOD (L4 Congestion)..." -ForegroundColor Red
        docker compose -f $ComposeFile --profile qos-demo up -d qos-flooder | Out-Null
        Start-Sleep -Seconds 2
        
        # Check if hping3 is available
        $hasHping = docker exec inline-qos-flooder sh -lc 'command -v hping3 >/dev/null && echo ok' 2>$null
        if ($hasHping -eq "ok") {
            Write-Host "         -> Starting hping3 SYN Flood..." -ForegroundColor Yellow
            # Kill any existing hping3 processes
            docker exec inline-qos-flooder sh -lc 'pkill -f hping3 >/dev/null 2>&1 || true'
            
            # Start flood attack targeting unknown port (9999) to be classified as P3
            # Target: 172.20.140.10 (opcua-server dst network) so traffic goes through QoS router
            # Using --rand-source to generate high volume of packets from random IPs
            docker exec inline-qos-flooder sh -lc 'hping3 --flood --rand-source -S -p 9999 172.20.140.10 >/tmp/hping_inline.log 2>&1 &'
            Start-Sleep -Seconds 2
            
            # Verify if hping3 is running (pgrep available after procps install)
            $hpingRunning = docker exec inline-qos-flooder sh -lc 'pgrep -f hping3 >/dev/null && echo running' 2>$null
            if ($hpingRunning -eq "running") {
                Write-Host "         -> ✅ hping3 SYN Flood active on 172.20.140.10:9999" -ForegroundColor Green
                Write-Host "         -> Flood traffic classified as P3, will be dropped by QoS" -ForegroundColor Gray
            } else {
                Write-Host "         -> ⚠️  hping3 may not be running (check container logs)" -ForegroundColor Yellow
                Write-Host "         -> Run: docker exec inline-qos-flooder cat /tmp/hping_inline.log" -ForegroundColor Gray
            }
        }
        else {
            Write-Host "         -> ⚠️  hping3 not found in container" -ForegroundColor Yellow
        }
        Write-Host "         -> Waiting 10s for network effects..." -ForegroundColor Yellow
        Start-Sleep -Seconds 10
    }

    foreach ($currentProtocol in $protocols) {
        $service = "$currentProtocol-attacker"
        Write-Host "`n[attack] Start $service (L7 Attack)" -ForegroundColor Yellow
        docker compose -f $ComposeFile up -d --build $service

        if ($protocols.Count -gt 1) {
            Write-Host "[attack] Wait ${BetweenAttackWaitSeconds}s before next attacker" -ForegroundColor Yellow
            Start-Sleep -Seconds $BetweenAttackWaitSeconds
        }
    }
}

function Show-Verification {
    Write-Host "`n[verify] Blacklist tail" -ForegroundColor Cyan
    Get-Content .\zeek_scripts\blacklist.acl -Tail 10
    Write-Host "`n[verify] ACTIVE_BLOCK chain" -ForegroundColor Cyan
    docker exec firewall-monitor iptables -L ACTIVE_BLOCK -n --line-numbers
    if ($WithFlood) {
        Write-Host "`n[verify] QoS Class Statistics (tc)" -ForegroundColor Cyan
        docker exec qos-router tc -s class show dev eth0
    }
}

switch ($Step) {
    "reset" { Reset-InlineArtifacts }
    "start" { Start-InlineBaseline }
    "attack" { Start-Attack }
    "verify" { Show-Verification }
    "full" {
        Reset-InlineArtifacts
        Start-InlineBaseline
        Write-Host "[full] Wait ${BaselineWaitSeconds}s for baseline telemetry" -ForegroundColor Yellow
        Start-Sleep -Seconds $BaselineWaitSeconds
        Start-Attack
        
        $effectiveFinalWait = $FinalWaitSeconds
        if ($Protocol -eq "all" -and $effectiveFinalWait -lt 150) { $effectiveFinalWait = 150 }
        Write-Host "[full] Wait ${effectiveFinalWait}s for pcap rotation, IDS monitor, and QoS tracking" -ForegroundColor Yellow
        Start-Sleep -Seconds $effectiveFinalWait
        Show-Verification
    }
}